version: '3'
services:
  api:
    build: "./go"
    ports:
      - "9090:9090"
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - backend

volumes:
  mongodata:  

networks:
  backend:
    driver: bridge